"""Lint the developer skills library. Exit 1 on any error.

Rules: valid YAML frontmatter with name (== folder, [a-z0-9-]) and description ("Use when …"); only known
keys; SKILL.md <= 300 lines with a References section; every referenced relative path exists; references
<= 400 lines; scripts executable with `set -euo pipefail`; no forbidden strings; external URLs listed in
docs/link_allowlist.txt; the AGENTS.md skills table matches the folders; generated schema.md is fresh.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
ALLOWED_KEYS = {"name", "description", "license", "compatibility", "metadata", "allowed-tools"}
FORBIDDEN = re.compile(r"\bgo/[a-z]|(?<![a-z/])cs/|google3|corp\.google|Proprietary|Confidential|INTERNAL\b|/Users/|/home/|Claude-Session|generated by Claude", re.I)
ULTA = re.compile(r"\bulta\b", re.I)
URL = re.compile(r"https?://[^\s)>\]`'\"]+")
NAME = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


def frontmatter(text: str) -> dict:
    if not text.startswith("---\n"):
        raise ValueError("frontmatter must start on line 1 with ---")
    end = text.find("\n---", 4)
    if end < 0:
        raise ValueError("frontmatter not closed")
    return yaml.safe_load(text[4:end]) or {}


def main() -> int:
    errors: list[str] = []
    allow = set()
    allow_file = ROOT / "docs" / "link_allowlist.txt"
    if allow_file.exists():
        allow = {line.strip() for line in allow_file.read_text().splitlines() if line.strip() and not line.startswith("#")}
    names = []
    for skill_dir in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        sk = skill_dir / "SKILL.md"
        if not sk.exists():
            errors.append(f"{skill_dir.name}: missing SKILL.md")
            continue
        text = sk.read_text()
        names.append(skill_dir.name)
        try:
            fm = frontmatter(text)
        except ValueError as e:
            errors.append(f"{skill_dir.name}: {e}")
            continue
        if fm.get("name") != skill_dir.name or not NAME.match(str(fm.get("name", ""))):
            errors.append(f"{skill_dir.name}: frontmatter name must equal the folder name")
        desc = str(fm.get("description", ""))
        if not (1 <= len(desc) <= 1024) or "Use when" not in desc:
            errors.append(f"{skill_dir.name}: description must be 1-1024 chars and say 'Use when …'")
        if set(fm) - ALLOWED_KEYS:
            errors.append(f"{skill_dir.name}: unknown frontmatter keys {sorted(set(fm) - ALLOWED_KEYS)}")
        if not (fm.get("metadata") or {}).get("verified"):
            errors.append(f"{skill_dir.name}: metadata.verified missing")
        if len(text.splitlines()) > 300:
            errors.append(f"{skill_dir.name}: SKILL.md longer than 300 lines")
        if "## References" not in text:
            errors.append(f"{skill_dir.name}: missing '## References' section")
        for f in skill_dir.rglob("*"):
            if f.is_dir() or "__pycache__" in f.parts:
                continue
            body = f.read_text(errors="replace")
            if FORBIDDEN.search(body):
                errors.append(f"{f.relative_to(ROOT)}: forbidden string {FORBIDDEN.search(body).group(0)!r}")
            if ULTA.search(body):
                errors.append(f"{f.relative_to(ROOT)}: 'Ulta' is not allowed under skills/")
            if f.suffix == ".md" and f.name != "SKILL.md" and len(body.splitlines()) > 400:
                errors.append(f"{f.relative_to(ROOT)}: reference longer than 400 lines")
            if f.parent.name == "scripts":
                if not os.access(f, os.X_OK):
                    errors.append(f"{f.relative_to(ROOT)}: script is not executable")
                if f.suffix == ".sh" and "set -euo pipefail" not in body:
                    errors.append(f"{f.relative_to(ROOT)}: shell script lacks 'set -euo pipefail'")
            for url in URL.findall(body):
                url = url.rstrip(".,;:")
                if "googleapis.com/auth/" in url or "<" in url or "{" in url or "$" in url or "}" in url or url.startswith("http://localhost"):
                    continue  # OAuth scopes, placeholders and localhost are not links
                if not any(url.startswith(a) for a in allow):
                    errors.append(f"{f.relative_to(ROOT)}: URL not in docs/link_allowlist.txt: {url}")
            for rel in re.findall(r"`((?:references|scripts)/[A-Za-z0-9_./-]+)`", body):
                if not (skill_dir / rel).exists() and not (ROOT / rel).exists() and not (ROOT / "quickstarts" / "08-mcp-tools-agent" / rel.split("/", 1)[-1]).exists():
                    errors.append(f"{f.relative_to(ROOT)}: referenced file missing: {rel}")
    agents_md = ROOT / "AGENTS.md"
    if agents_md.exists():
        listed = set(re.findall(r"`?skills/([a-z0-9-]+)/SKILL\.md`?", agents_md.read_text()))
        if listed != set(names):
            errors.append(f"AGENTS.md skills table != folders: missing {sorted(set(names) - listed)}, extra {sorted(listed - set(names))}")
    else:
        errors.append("AGENTS.md missing at the repo root")
    gen = SKILLS / "cymbal-beauty-domain" / "scripts" / "gen_schema_md.py"
    if gen.exists():
        out = subprocess.run([sys.executable, str(gen), "--stdout"], capture_output=True, text=True)
        current = (SKILLS / "cymbal-beauty-domain" / "references" / "schema.md").read_text()
        if out.returncode == 0 and out.stdout.strip() and out.stdout.strip() != current.strip():
            errors.append("cymbal-beauty-domain/references/schema.md is stale: run scripts/gen_schema_md.py")
    for e in errors:
        print(f"[FAIL] {e}")
    print(f"{len(names)} skills checked, {len(errors)} error(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
