"""Run bounded release-browser checks only after an explicit deployment-ready signal.

Opening submits exactly one chat request. Workspace submits exactly one event and
previews an already-generated PDF supplied by the release owner. Neither phase
approves writes, retries a failed model request, or changes model settings.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
URL = "https://cymbal-frontend-demo-dev-763419985448.us-central1.run.app"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-live", action="store_true")
    parser.add_argument("--phase", required=True, choices=("opening", "workspace"))
    parser.add_argument("--runtime-revision", required=True, help="Deployment owner's verified revision label")
    parser.add_argument("--url", default=URL)
    parser.add_argument("--pdf", type=Path, help="Actual PDF generated on the new runtime; required for workspace")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    if not args.run_live:
        parser.error("Pass --run-live only after the deployment-ready signal; no network request was sent")
    if args.phase == "workspace" and (not args.pdf or not args.pdf.is_file()):
        parser.error("Workspace requires --pdf pointing to the newly generated release PDF")
    args.out.mkdir(parents=True, exist_ok=True)
    manifest = {"phase": args.phase, "deployment_owner_revision": args.runtime_revision,
                "revision_verification": "Provided by release owner; this script verifies browser behavior",
                "agent_invocations_requested": 1, "automatic_probe_resubmission": False}
    if args.phase == "opening":
        command = [sys.executable, str(ROOT / "scripts/check_live_tablet.py"), "--run-live", "--opening-only",
                   "--timeout", "240", "--url", args.url, "--out", str(args.out)]
    else:
        pdf = args.pdf.resolve()
        manifest["pdf"] = {"path": str(pdf), "sha256": hashlib.sha256(pdf.read_bytes()).hexdigest(),
                           "provenance": "Generated by the release owner's new-runtime probe; staged into this browser's owned session only for preview/download checks"}
        command = [sys.executable, str(ROOT / "scripts/check_workspace_experience.py"), "--run-event",
                   "--url", args.url, "--secret", "cymbal-frontend-demo-dev-password", "--timeout", "300",
                   "--pdf", str(pdf), "--out", str(args.out)]
    (args.out / "release-probe-manifest.json").write_text(json.dumps(manifest, indent=2))
    return subprocess.run(command, cwd=ROOT, check=False).returncode


if __name__ == "__main__":
    raise SystemExit(main())
