"""Check documentation links, image paths, formatting and public-facing content.

The notebooks are the workshop labs. Markdown pages provide setup, source and
platform references. Notebook links and execution are validated separately by
the notebooks themselves (executed top to bottom before a release).
"""
from __future__ import annotations

import argparse
import concurrent.futures
import re
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST = ROOT / "docs" / "link_allowlist.txt"

SKIP_DIRS = {".venv", ".git", "node_modules", "__pycache__", ".pytest_cache", ".ruff_cache", ".adk", "dist",
             "build", "_4k", ".idea", ".vscode", ".agents", ".claude", ".gemini", "out"}
TEXT_SUFFIXES = {".md", ".py", ".yaml", ".yml", ".sh", ".txt", ".json", ".toml", ".cfg", ".ini", ".env", ".example"}
TEXT_NAMES = {"Makefile", ".env.example", "Dockerfile"}

ULTA_ALLOWED = ("docs/diagrams/prompts/07-", "docs/diagrams/prompts/08-",
                "docs/diagrams/prompts/09-", "docs/diagrams/README.md", "scripts/check_docs.py", "scripts/check_skills.py",
                "tests/quickstarts/test_catalog.py", "docs/link_allowlist.txt", "docs/diagrams/prompts/_creative_direction.md")
SELF_EXEMPT = ("scripts/check_docs.py", "scripts/check_skills.py")  # they contain the forbidden patterns by design
ULTA = re.compile(r"\bulta\b", re.I)

FORBIDDEN: list[tuple[str, re.Pattern[str]]] = [
    ("personal path", re.compile(r"/Users/")),
    ("AI attribution", re.compile(r"Claude-Session|claude\.ai/code/session|Co-Authored-By: Claude", re.I)),
    ("AI attribution", re.compile(r"generated (by|with) (claude|anthropic|an? ai\b|ai assistant|a language model|an? llm|chatgpt|codex|gpt-?\d)", re.I)),
    ("internal reference", re.compile(r"\bgo/[a-z]|\bgoogle3\b|corp\.google|\bcs/[a-z]|\bJetski\b|\bArgolis\b|\bConcord\b")),
    ("internal marking", re.compile(r"Proprietary\s*(&|and|\+)\s*Confidential|Internal Distribution Only|Do not share externally|INTERNAL ONLY", re.I)),
    ("Googler email", re.compile(r"[A-Za-z0-9._%+-]+@google\.com")),
]
VENDOR_FORBIDDEN = re.compile(r"\bHarness\b|harness\.io|(?i:\bbitbucket\b|\bdatabricks\b|\bmlflow\b|unity catalog)")   # the CI product, not the English word
VENDOR_ALLOWED = ("docs/CONNECTING_TO_DATA.md", "docs/PROMOTION_STRATEGY.md",
                  "skills/bitbucket-integration/",                  # the one skill about that platform
                  "docs/link_allowlist.txt")                        # URL prefixes, not prose
VENDOR_SKILL_TOKEN = "bitbucket-integration"  # a line that names that skill (a table row, a command) may say what it is for
GENERATED_BY = re.compile(r"\bgenerated by\b", re.I)
EMOJI = re.compile("[\U0001F000-\U0001FAFF☀-⚟⚡-➿⭐⭕⌚-⏿]")
WARNING_SIGN = "⚠"

IMG_MD = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
IMG_HTML = re.compile(r"<img\b[^>]*>", re.I)
LINK_MD = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
URL_RAW = re.compile(r"https?://[^\s<>\"'`)\]]+")
FENCE = re.compile(r"^\s*(`{3,}|~{3,})(.*)$")
AGENT_ENGINE = re.compile(r"Agent Engine")
AGENT_RUNTIME_PHRASE = "Agent Runtime (formerly Agent Engine)"


@dataclass
class Finding:
    level: str
    path: str
    line: int
    message: str


class Report:
    def __init__(self, strict: bool) -> None:
        self.strict = strict
        self.rows: list[Finding] = []

    def fail(self, path: Path, line: int, msg: str) -> None:
        self.rows.append(Finding("FAIL", rel(path), line, msg))

    def warn(self, path: Path, line: int, msg: str) -> None:
        self.rows.append(Finding("FAIL" if self.strict else "WARN", rel(path), line, msg))


def rel(p: Path) -> str:
    try:
        return str(p.resolve().relative_to(ROOT))
    except ValueError:
        return str(p)


def is_text(p: Path) -> bool:
    return p.suffix in TEXT_SUFFIXES or p.name in TEXT_NAMES


def discover(paths: list[str]) -> list[Path]:
    roots = [ROOT / p if not Path(p).is_absolute() else Path(p) for p in paths] or [ROOT]
    files: list[Path] = []
    for r in roots:
        if r.is_file():
            files.append(r)
            continue
        for p in sorted(r.rglob("*")):
            if any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts):
                continue
            if p.is_file() and is_text(p):
                files.append(p)
    return files


def normalize_url(u: str) -> str:
    u = u.rstrip(".,;:!?)")
    u = u.split("#", 1)[0]
    return u.rstrip("/")


def load_allowlist() -> set[str]:
    if not ALLOWLIST.exists():
        return set()
    return {normalize_url(line.strip()) for line in ALLOWLIST.read_text().splitlines()
            if line.strip() and not line.strip().startswith("#")}


def markdown_lines(text: str):
    """Yield (line_no, line, in_fence, fence_lang, opener) for every line, tracking fenced code blocks."""
    fence_char, fence_len, lang = "", 0, ""
    for i, line in enumerate(text.splitlines(), start=1):
        m = FENCE.match(line)
        if m:
            marker, rest = m.group(1), m.group(2).strip()
            if not fence_char:
                fence_char, fence_len, lang = marker[0], len(marker), rest.split()[0] if rest else ""
                yield i, line, True, lang, True
                continue
            if marker[0] == fence_char and len(marker) >= fence_len and not rest:
                yield i, line, True, lang, False
                fence_char, fence_len, lang = "", 0, ""
                continue
        yield i, line, bool(fence_char), lang, False


def check_markdown(p: Path, text: str, allow: set[str], rep: Report, online_urls: dict[str, tuple[Path, int]]) -> None:
    r = rel(p)
    lab_file = r == "SETUP.md" or r.startswith("notebooks/")
    h1, h2s, h2_lines = [], [], []
    prose = []  # (line_no, line) outside fences
    bash_fences = []  # line numbers of bash fence openers
    fence_openers = []  # (line_no, lang)
    for no, line, in_fence, lang, opener in markdown_lines(text):
        if opener:
            fence_openers.append((no, lang))
            if lang in ("bash", "sh", "shell", "console"):
                bash_fences.append(no)
            continue
        if in_fence:
            continue
        prose.append((no, line))
        if line.startswith("# "):
            h1.append(line[2:].strip())
        elif line.startswith("## "):
            h2s.append(line[3:].strip())
            h2_lines.append(no)

    for no, lang in fence_openers:
        if not lang:
            rep.fail(p, no, "code fence without a language tag (use bash, text, python, yaml, json, sql ...)")

    for no, line in prose:
        for m in IMG_MD.finditer(line):
            alt, src = m.group(1).strip(), m.group(2)
            if not alt:
                rep.fail(p, no, f"image without alt text: {src}")
            check_image_path(p, no, src, rep)
        for m in IMG_HTML.finditer(line):
            tag = m.group(0)
            alt = re.search(r"alt=\"([^\"]*)\"", tag)
            src = re.search(r"src=\"([^\"]*)\"", tag)
            if not alt or not alt.group(1).strip():
                rep.fail(p, no, "image without alt text: <img>")
            if src:
                check_image_path(p, no, src.group(1), rep)
        for m in LINK_MD.finditer(line):
            target = m.group(2)
            if target.startswith(("http://", "https://")):
                continue  # handled with the raw URL scan below
            if target.startswith(("mailto:", "tel:")):
                continue
            if target.startswith("/"):
                rep.fail(p, no, f"root-relative link {target}: use a path relative to this file")
                continue
            path_part = target.split("#", 1)[0]
            if not path_part:
                continue
            if not (p.parent / path_part).exists():
                rep.fail(p, no, f"relative link does not resolve: {target}")
        for m in URL_RAW.finditer(line):
            url = normalize_url(m.group(0))
            if re.match(r"https?://(localhost|127\.0\.0\.1|0\.0\.0\.0|<)", url):
                continue
            if not any(url == a or url.startswith(a) for a in allow):
                rep.fail(p, no, f"external link not in docs/link_allowlist.txt: {url}")
            else:
                online_urls.setdefault(url, (p, no))
        if EMOJI.search(line):
            rep.fail(p, no, "emoji in prose")
        if WARNING_SIGN in line:
            rep.warn(p, no, "⚠ marker left in the text (resolve or drop before delivery)")

    prose_text = "\n".join(line for _, line in prose)
    if AGENT_ENGINE.search(prose_text) and r.split("/")[0] in ("README.md", "SETUP.md", "notebooks", "docs", "quickstarts"):
        first_phrase = prose_text.find(AGENT_RUNTIME_PHRASE)
        first_engine = AGENT_ENGINE.search(prose_text).start()
        if first_phrase == -1 or first_engine < first_phrase:
            rep.warn(p, 1, 'say "Agent Runtime (formerly Agent Engine)" on first use, "Agent Runtime" after')

    if lab_file:
        lines = text.splitlines()
        for no in bash_fences:
            # find the closing fence, then the next non-blank line must open another fence (the expected output)
            j = no
            while j < len(lines) and not FENCE.match(lines[j]):
                j += 1
            k = j + 1
            while k < len(lines) and not lines[k].strip():
                k += 1
            # Either the classic shape (an output fence or an "Expected:" line straight after the command), or the
            # guided shape, where a "**Check.**" item follows the Run block within a few lines of timing prose.
            ahead = [ln for ln in lines[j + 1:j + 12] if ln.strip()][:5]
            guided = any(ln.lstrip("-> *").startswith("Check.") or "**Check.**" in ln for ln in ahead)
            if k >= len(lines) or not (FENCE.match(lines[k]) or lines[k].lstrip("> *").startswith("Expected") or guided):
                rep.warn(p, no, "command block not followed by an expected-output block, an 'Expected:' line or a '**Check.**' item")


def check_image_path(p: Path, no: int, src: str, rep: Report) -> None:
    if src.startswith(("http://", "https://")):
        return
    if src.startswith("/"):
        rep.fail(p, no, f"root-relative image path {src}")
        return
    target = p.parent / src.split("#", 1)[0]
    if target.exists():
        return
    if "docs/diagrams/" in str(target.resolve()) and src.endswith(".png"):
        rep.warn(p, no, f"diagram not delivered yet: {src}")
    else:
        rep.fail(p, no, f"image path does not resolve: {src}")


def check_text(p: Path, text: str, rep: Report) -> None:
    r = rel(p)
    if r.startswith(SELF_EXEMPT):
        return
    ulta_ok = r.startswith(ULTA_ALLOWED)
    in_extend = False
    for no, line in enumerate(text.splitlines(), start=1):
        if r.startswith("quickstarts/") and line.startswith("## "):
            in_extend = line.lower().startswith("## extend it for ulta")
        if not ulta_ok and not in_extend and ULTA.search(line):
            rep.fail(p, no, '"Ulta" outside customer research or approved diagrams')
        if not r.startswith(VENDOR_ALLOWED) and VENDOR_SKILL_TOKEN not in line and VENDOR_FORBIDDEN.search(line):
            rep.fail(p, no, "third-party platform named outside docs/CONNECTING_TO_DATA.md, docs/PROMOTION_STRATEGY.md and its own skill")
        for label, pat in FORBIDDEN:
            if pat.search(line):
                rep.fail(p, no, f"forbidden ({label}): {pat.search(line).group(0)!r}")
        if p.suffix == ".md" and GENERATED_BY.search(line) and not FORBIDDEN[2][1].search(line):
            rep.warn(p, no, '"generated by": make sure this is not an attribution note')


def head(url: str) -> tuple[str, int | str]:
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "Mozilla/5.0 (docs-lint)"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return url, resp.status
    except urllib.error.HTTPError as e:
        if e.code in (403, 405):
            try:
                req = urllib.request.Request(url, method="GET", headers={"User-Agent": "Mozilla/5.0 (docs-lint)"})
                with urllib.request.urlopen(req, timeout=20) as resp:
                    return url, resp.status
            except urllib.error.HTTPError as e2:
                return url, e2.code
            except Exception as e2:  # noqa: BLE001
                return url, type(e2).__name__
        return url, e.code
    except Exception as e:  # noqa: BLE001
        return url, type(e).__name__


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="*", help="files or directories (default: whole repo)")
    ap.add_argument("--online", action="store_true", help="request every referenced external URL")
    ap.add_argument("--strict", action="store_true", help="treat WARN as FAIL (delivery mode)")
    a = ap.parse_args()
    rep = Report(strict=a.strict)
    allow = load_allowlist()
    if not allow:
        rep.fail(ALLOWLIST, 1, "docs/link_allowlist.txt is missing or empty")
    online_urls: dict[str, tuple[Path, int]] = {}
    files = discover(a.paths)
    for p in files:
        try:
            text = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            rep.fail(p, 1, "not valid UTF-8")
            continue
        check_text(p, text, rep)
        if p.suffix == ".md":
            check_markdown(p, text, allow, rep, online_urls)
    if a.online and online_urls:
        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
            for url, status in ex.map(head, sorted(online_urls)):
                if not (isinstance(status, int) and status < 400):
                    p, no = online_urls[url]
                    rep.fail(p, no, f"link returned {status}: {url}")
    rep.rows.sort(key=lambda f: (f.level != "FAIL", f.path, f.line))
    for f in rep.rows:
        print(f"[{f.level}] {f.path}:{f.line}  {f.message}")
    fails = sum(1 for f in rep.rows if f.level == "FAIL")
    warns = sum(1 for f in rep.rows if f.level == "WARN")
    print(f"\n{len(files)} files checked, {fails} FAIL, {warns} WARN" + (f", {len(online_urls)} links requested" if a.online else ""))
    return 1 if fails else 0


if __name__ == "__main__":
    raise SystemExit(main())
